from Animal import Especie

animal1 = Especie("Cachorro", "Animalia", "Chordata", "Mammalia", "Carnivora", "Canidae", "Canis", "Canis lupus familiaris")
animal2 = Especie("Gato", "Animalia", "Chordata", "Mammalia", "Carnivora", "Felidae", "Felis", "Felis catus")
animal3 = Especie("Leão", "Animalia", "Chordata", "Mammalia", "Carnivora", "Felidae", "Panthera", "Panthera leo")
animal4 = Especie("Elefante Africano", "Animalia", "Chordata", "Mammalia", "Proboscidea", "Elephantidae", "Loxodonta", "Loxodonta africana")
animal5 = Especie("Tigre", "Animalia", "Chordata", "Mammalia", "Carnivora", "Felidae", "Panthera", "Panthera tigris")
animal6 = Especie("Girafa", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Giraffidae", "Giraffa", "Giraffa camelopardalis")
animal7 = Especie("Zebra", "Animalia", "Chordata", "Mammalia", "Perissodactyla", "Equidae", "Equus", "Equus quagga")
animal8 = Especie("Cavalo", "Animalia", "Chordata", "Mammalia", "Perissodactyla", "Equidae", "Equus", "Equus ferus caballus")
animal9 = Especie("Urso Pardo", "Animalia", "Chordata", "Mammalia", "Carnivora", "Ursidae", "Ursus", "Ursus arctos")
animal10 = Especie("Urso Polar", "Animalia", "Chordata", "Mammalia", "Carnivora", "Ursidae", "Ursus", "Ursus maritimus")
animal11 = Especie("Lobo", "Animalia", "Chordata", "Mammalia", "Carnivora", "Canidae", "Canis", "Canis lupus")
animal12 = Especie("Raposa", "Animalia", "Chordata", "Mammalia", "Carnivora", "Canidae", "Vulpes", "Vulpes vulpes")
animal13 = Especie("Leopardo", "Animalia", "Chordata", "Mammalia", "Carnivora", "Felidae", "Panthera", "Panthera pardus")
animal14 = Especie("Jaguar", "Animalia", "Chordata", "Mammalia", "Carnivora", "Felidae", "Panthera", "Panthera onca")
animal15 = Especie("Canguru", "Animalia", "Chordata", "Mammalia", "Diprotodontia", "Macropodidae", "Macropus", "Macropus rufus")
animal16 = Especie("Coala", "Animalia", "Chordata", "Mammalia", "Diprotodontia", "Phascolarctidae", "Phascolarctos", "Phascolarctos cinereus")
animal17 = Especie("Ornitorrinco", "Animalia", "Chordata", "Mammalia", "Monotremata", "Ornithorhynchidae", "Ornithorhynchus", "Ornithorhynchus anatinus")
animal18 = Especie("Equidna", "Animalia", "Chordata", "Mammalia", "Monotremata", "Tachyglossidae", "Tachyglossus", "Tachyglossus aculeatus")
animal19 = Especie("Golfinho", "Animalia", "Chordata", "Mammalia", "Cetacea", "Delphinidae", "Delphinus", "Delphinus delphis")
animal20 = Especie("Baleia Azul", "Animalia", "Chordata", "Mammalia", "Cetacea", "Balaenopteridae", "Balaenoptera", "Balaenoptera musculus")
animal21 = Especie("Morcego", "Animalia", "Chordata", "Mammalia", "Chiroptera", "Vespertilionidae", "Myotis", "Myotis lucifugus")
animal22 = Especie("Rinoceronte", "Animalia", "Chordata", "Mammalia", "Perissodactyla", "Rhinocerotidae", "Rhinoceros", "Rhinoceros unicornis")
animal23 = Especie("Hipopótamo", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Hippopotamidae", "Hippopotamus", "Hippopotamus amphibius")
animal24 = Especie("Tartaruga Marinha", "Animalia", "Chordata", "Reptilia", "Testudines", "Cheloniidae", "Chelonia", "Chelonia mydas")
animal25 = Especie("Cobra", "Animalia", "Chordata", "Reptilia", "Squamata", "Elapidae", "Naja", "Naja naja")

print(animal1.descricao()) 
print(animal2.descricao())
print(animal3.descricao()) 
print(animal4.descricao()) 
print(animal5.descricao()) 
print(animal6.descricao()) 
print(animal7.descricao()) 
print(animal8.descricao()) 
print(animal9.descricao()) 
print(animal10.descricao()) 
print(animal11.descricao()) 
print(animal12.descricao()) 
print(animal13.descricao()) 
print(animal14.descricao())
print(animal15.descricao()) 
print(animal16.descricao()) 
print(animal17.descricao()) 
print(animal18.descricao()) 
print(animal19.descricao()) 
print(animal20.descricao()) 
print(animal21.descricao()) 
print(animal22.descricao()) 
print(animal23.descricao()) 
print(animal24.descricao()) 
print(animal25.descricao()) 